### ISSUE TITLE
Cannot create item: item with the same key

### ISSUE THREAD

**Issue by seregawerewolf** [nobody43/zabbix-smartmontools#12]
After installation in "detection" of a host hangs an exclamation mark with an error:
Cannot create item: item with the same key "smartctl.info[{#DDRIVESTATUS},DriveStatus]" already exists.

Who can faced a problem?

**Comment by nobodysu** [comment]
Everyone are facing this problem. :)
It's a cosmetic problem, it will not affect the result, though a solution is planned - #7.

Are you getting keys created in web interface? Data acquisition after 12-24 hours? What about [Testing](https://github.com/nobodysu/zabbix-smartmontools#testing)?

**Comment by seregasoft** [comment]
Hi!
There is no such error on the first server, LLD creates items and data arrives.
But the error "Cannot create item: item with the same key "smartctl.info[{#DDRIVESTATUS},DriveStatus]" already exists" appears on the second server. LLD creates items but I don't receive data

**Comment by nobodysu** [comment]
This is expected, it should not interfere with the actual process.
What about previous suggestions?
`sender_wrapper.py` should be at: `/usr/local/etc/zabbix/scripts/sender_wrapper.py`

**Comment by seregasoft** [comment]
Thanks, "smartctl.discovery [**getverb**, "my_host"]" helped solve the problem:
Error was:
"my_host" smartctl.info [ConfigStatus] "CONFIGURED" zabbix_sender [54746]: DEBUG: send value error: cannot resolve [old_zabbix_host.stc]

For some reason zabbix-smartmontools used the old zabbix agent configuration /usr/local/etc/zabbix22/zabbix_agentd.conf where old_zabbix_host.stc was specified
Although the current configuration in /usr/local/etc/zabbix5/zabbix_agentd.conf

Changed in /usr/local/etc/zabbix22/zabbix_agentd.conf Server and ServerActive to the actual address of Zabbix Server and now the data values come. Thank!

**Comment by nobody43** [comment]
Supersedes: https://github.com/nobody43/zabbix-smartmontools/issues/7
