### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by CheckB** [nobody43/zabbix-smartmontools#17]
1. I suggest to take some functionality from here: https://github.com/v-zhuravlev/zbx-smartctl https://github.com/rmalenko/zabbix 

2. Smart support for sata ssd

**Comment by nobodysu** [comment]
Yeah, I'm aware about these repos, but don't want to just copy the functionality straight away.

NVMe support is being worked on, SATA SSD support is planned.

**Comment by v-zhuravlev** [comment]
Hi, @nobodysu , I'm planning to rewrite https://github.com/v-zhuravlev/zbx-smartctl to python to let more contributors in and also to add some python unittests for better scripts stability. Maybe you are interested to join forces for better smart monitoring in Zabbix?

**Comment by nobodysu** [comment]
@v-zhuravlev , hi!
I'm all in for cooperation - that's for sure! However, I believe public zabbix additions must have certain features, with which you may disagree:
- It must support all Zabbix LTS and Debian/Centos LTS without inconsistencies. That means no Dependent Items.
- It must spawn absolute minimum number of processes
- Lowest overhead when possible - that means mostly trapper.

I mostly dislike my current approach with running second script in background, but not really sure there is a way to improve it without much overhead. Maybe separate LLD and individual per-disk trapper and use cache file as a last resort. Also not sure could LLD be properly grouped or not (https://github.com/nobodysu/zabbix-smartmontools/issues/8).

Let me know what you think about my view.

**Comment by nobodysu** [comment]
@v-zhuravlev 
Are that restrictions too much for you? :)
Its discussable - state your point.

**Comment by nobodysu** [comment]
@v-zhuravlev
Можно по-русски: e@mdmart.ru

**Comment by v-zhuravlev** [comment]
@nobodysu, I'm for sure against trapper here. 

I personally prefer to work using this in mind first:
- Templates must be self contained as possible. So, less external dependencies (scripts, trappers, etc) - better. It makes it easier for end users to install and use
- If you have to use external dependencies - prefer something that is available on most distributions with less additional packages as possible(so, core python 2.x for Linux for instance, or powershell for Windows)

I suggest another approach. There is already smartctl solution for Zabbix version 3.0 working(like yours)
So maybe a more simple solution can be developed for 4.0 and 4.2 now with current smartctl solutions gradually phased out later on.

**Comment by nobodysu** [comment]
@v-zhuravlev 
I'm ok to ditch trapper in favor for per-disk text cache file, if that's the case.

Also, I'm a little concerned about DI, can you clear some things out?
- Does DI have a timeout trigger in case of unresponsive disk failure?
- Does it handle process return code? ([DRIVESTATUS](https://github.com/nobodysu/zabbix-smartmontools/blob/master/screenshots/smartctl_discovery_triggers1.png))
- Does it have some sort of post-processing e.g. if output contains A and B but not C then <trigger>? ([1](https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/mini_ipmi_smartctl.py#L173-L182), [2](https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/mini_ipmi_smartctl.py#L340-L352), [3](https://github.com/nobodysu/zabbix-mini-IPMI/blob/master/mini_ipmi_smartctl.py#L374-L383))

A thought: maybe wrap per-disk smartctl call with a wrapper, and return output + logic result for DI?
If that's not possible in some way or another, I'm afraid I can't go with DI.

Also I can't write in PowerShell.

**Comment by v-zhuravlev** [comment]
@nobodysu 
Sorry for long delays.
I like your questions, it shows that you know what your are doing.

> Does DI have a timeout trigger in case of unresponsive disk failure?
- For the start, a simple nodata(30m) trigger would help here.

> Does it handle process return code? (DRIVESTATUS)

- You still need UserParameter for DI, so simple bash command can help you to append the return code to the output of the smartctl.

> Does it have some sort of post-processing e.g. if output contains A and B but not C then ? (1, 2, 3)

This can be achieved using JavaScript preprocessing in 4.2

**Comment by nobodysu** [comment]
@v-zhuravlev
Alright.
What about python for Windows, can you go with it? I think different implementation languages and features will cause confusion to the end user. Also I'm not going to learn or endorse proprietary solutions like PowerShell. I will learn some JS basics fro DI, however.
Really looking forward for cooperation to happen, and it will be really sad if I will not be able to work on Windows version.

**Comment by v-zhuravlev** [comment]
@nobodysu ,
I believe that agent-side should require discovery only scripts.  And I suggest that it would really great if this discovery can happen without installing python interpreter on each windows host you might need to monitor disks, so:
- It's not necessary to learn powershell, although it's not that bad. PS Discovery script is already present and can be used. I can keep an eye on it.
- Python script still can be written to support Windows

>I think different implementation languages and features will cause confusion to the end user.

Not really, if input and output of the script is the same for Windows and Nix versions.

**Comment by nobodysu** [comment]
@v-zhuravlev 
I thought it out many times and realized I can't drop 3.0 LTS.
I have many zabbix additions already and can't change my infrastructure entirely. Therefore, I will not be able to test 4.2 solutions extensively, and that's defeats the entire purpose.

For 3.0+, I'm still proposing per-disk cache file (DI substitute), no sender and python-only (JS PP substitute) solution. But afraid you won't like it.
