### ISSUE TITLE
Don't report duplicates to Zabbix

### ISSUE THREAD

**Issue by asomers** [nobody43/zabbix-smartmontools#36]
Currently if `skipDuplicates` is true, zabbix-smartmontools will report the duplicate device during discovery, but list its status as "Duplicate".  I think it would make sense to simply not report it at all.  Do you agree?

**Comment by nobodysu** [comment]
I learned the hard way that flapping isn't good. That's why JSON for any disk is always reported.
You can implement `duplicates = 'skip'` and `duplicates = 'hide'`.
