### ISSUE TITLE
LLD & server timeouts

### ISSUE THREAD

**Issue by automatize-it** [nobody43/zabbix-smartmontools#44]
More like comment/FAQ enhancement:
For some systems, server default timeout (3 seconds) is not enough for LLD scenario to complete on client. In my case, LLD on client W7/Core i5 with 3 HDDs takes about 5 seconds to complete.

**Comment by nobody43** [comment]
Thank you! I'll mention it.

**Comment by nobody43** [comment]
Done, thanks.
