### ISSUE TITLE
Installation & folders

### ISSUE THREAD

**Issue by automatize-it** [nobody43/zabbix-smartmontools#45]
While install under Windows, setup creates C:\zabbix-agent\zabbix-smartmontools folder that contains zabbix-smartmontools.conf file. 
Then
`move zabbix-smartmontools.conf C:\zabbix-agent\
move Win\zabbix_agentd.conf.d\userparameter_smartctl.conf C:\zabbix-agent\zabbix_agentd.conf.d\`
is needed, and C:\zabbix-agent\zabbix-smartmontools is not used. It is kinda confusing.

Also, it could be great to choose/change installation folder. Maybe just add info where to do it in setup file.

**Comment by nobody43** [comment]
I will clear this up in the new version.

**Comment by nobody43** [comment]
Returned to a previous unpackaged version - it's no longer an issue.
Also updated the paths to never ones.
