### ISSUE TITLE
since smartmontool already is run for each drive, why not pull the temperature as well ?

### ISSUE THREAD

**Issue by bschwand** [nobody43/zabbix-smartmontools#54]
**Is your feature request related to a problem? Please describe.**

running smartctl for each drive already takes a relatively long time, why run it twice if we want drive temperatures ?

**Describe the solution you'd like**
You mention temperatures are retrieved with mini-ipmi, it would be more efficient if mini-ipmi did not use smartctl (or only optionally) and let this (zabbix-smartmontools scripts) get the temperatures.

**Describe alternatives you've considered**
running mini-IPMI as well...

**Comment by nobody43** [comment]
The reasons for not handling temperatures with `zabbix-smartmontools` are:
- `zabbix-smartmontools` have marginally larger data footprint, it's wasteful to run it every 22 minutes
- decreasing `zabbix-smartmontools` run cycles will produce more spin-ups on some systems, reducing drive's lifetime
- I don't have free time to interconnect `zabbix-smartmontools` and `zabbix-mini-IPMI` for efficient operation, and even if I did, it would be configuration hell for the user
- I plan to collect all drive temperature history on `zabbix-mini-IPMI`, it will be an additional `smartctl` call anyway

**Comment by bschwand** [comment]
> The reasons for not handling temperatures with `zabbix-smartmontools` are:
> 
> * `zabbix-smartmontools` have marginally larger data footprint, it's wasteful to run it every 22 minutes

right, so that is why I suggest to run it less overall

> * decreasing `zabbix-smartmontools` run cycles will produce more spin-ups on some systems, reducing drive's lifetime

but you just said you want to run it less often ?

> * I don't have free time to interconnect `zabbix-smartmontools` and `zabbix-mini-IPMI` for efficient operation, and even if I did, it would be configuration hell for the user

no need to interconnect anything

> * I plan to collect all drive temperature history on `zabbix-mini-IPMI`, it will be an additional `smartctl` call anyway

so it will call smartctl too ? increasing the number of calls
and why collect drive temperatures in the ipmi tool ?

I do not understand your answer I am even more confused. My whole point is : what is the point or running a tool twice for the same data. An accessory point is why take data from one data set (drives) and shove it into another (ipmi)

zabbix-smartmontools runs smartctl already, so it already has the drives temperatures. My point is that when just running smartmontools, the temperatures are there, they just need to be parsed out of the smartctl output, since it's already part of the data collected, might as well put it in that template.

but in the current setup, zabbix-miniIPMI then runs, again smartctl.

so, as far as I understand, smartctl is run twice when it could run once.

I do not suggest any interconnect between the two (miniIPMI/smartmon). 

I must be missing something here but I do not see the advantage in mixing datas ources in this case. Normal IPMI already does not provide drive temperatures, but just some chassis and cpu temperatures.

**Comment by nobody43** [comment]
> PS: your answer makes sense if smartmontool runs smartctl rarely (once a day) and miniIPMI would run it often.

That's correct. By default `zabbix-smartmontools` runs every 12 hours and `zabbix-mini-IPMI` runs every 22 minutes (for drives). There's no need in temperature monitoring if it's not recent.
